[package]
name = "tail"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
notify = "6.1"
serde_json = "1.0"
colored = "2.1"
regex = "1.10"
